### ISSUE TITLE
doesn't work anymore

### ISSUE THREAD

**Issue by Yoposoc** [Patchonn/userscripts#1]
https://github.com/Patchonn/userscripts/blob/master/twitter-utils.user.js

pls fix
;_;

**Comment by yogthot** [comment]
What exactly stopped working?
It still works for me.

If they updated the UI I can't fix it until I get the new version.

**Comment by Yoposoc** [comment]
the image hover expander stopped working.
but now it does.
...

**Comment by yogthot** [comment]
I remembered the script wasn't running on the mobile domain, maybe that's why it wasn't working.
I fixed that now.
